/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.student;


import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.EmploymentHistory.EmploymentHistory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentProfile;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.MainJframe;

/**
 *
 * @author HYR
 */
public class Form extends javax.swing.JPanel {
    StudentProfile student;
    MainJframe main;
    EmploymentHistory employmentHistory;
    Department department;
    CourseSchedule courseSchedule;
    boolean complete = false;
    int i = 0;
    ArrayList<CourseOffer> c = new ArrayList();
    /**
     * Creates new form form1
     */
    public Form( StudentProfile student,MainJframe m,EmploymentHistory eh,Department d,CourseSchedule c) {
        initComponents();
        department = d;
        main = m;
        courseSchedule = c;
        this.student = student;
        this.employmentHistory = eh;
        populateCourseCombo();
        populateStudentCourses();
        populateFacultyScore();
        
    }
    public void populateCourseCombo() {
        cmbcourse.removeAllItems();
        for(CourseLoad cl:  student.getTranscript().getAllCourses()){
            cmbcourse.addItem(cl.getCourseOffer());
            
        }
    }
    public void populateStudentCourses(){
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0);        
        for(CourseOffer co : student.getRelevent()){
                Object row[] = new Object[2];
                row[0] = co;
                row[1] = co.getFacultyProfile().getPerson().getName();
                model.addRow(row);
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblpromotion = new javax.swing.JLabel();
        lblpromotion2 = new javax.swing.JLabel();
        lblworkyear = new javax.swing.JLabel();
        lblpromotion3 = new javax.swing.JLabel();
        txtworkyear = new javax.swing.JTextField();
        txtpromotiontime = new javax.swing.JTextField();
        txtcurrentsalary = new javax.swing.JTextField();
        txtstartSalary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbltop3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFacultyScore = new javax.swing.JTextField();
        btmsave = new javax.swing.JButton();
        btmBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btmAdd1 = new javax.swing.JButton();
        cmbcourse = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFacultyScore = new javax.swing.JTable();
        btmAdd2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        instructorLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Graduation survey");

        lblpromotion.setText("Promotion times");

        lblpromotion2.setText("Start Salary");

        lblworkyear.setText("Work Years(form 1 to 5)");

        lblpromotion3.setText("Current Salary");

        txtworkyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtworkyearActionPerformed(evt);
            }
        });

        txtpromotiontime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpromotiontimeActionPerformed(evt);
            }
        });

        txtcurrentsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcurrentsalaryActionPerformed(evt);
            }
        });

        txtstartSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartSalaryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 1, 11)); // NOI18N
        jLabel2.setText("Courses that you think have the greatest impact on your work ");

        lbltop3.setText("Pick relevent course");

        jLabel3.setText("Evaluate this instructor of the course(form 1 to 10)");

        btmsave.setBackground(new java.awt.Color(0, 153, 102));
        btmsave.setText("save");
        btmsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmsaveActionPerformed(evt);
            }
        });

        btmBack.setBackground(new java.awt.Color(204, 51, 0));
        btmBack.setText("Back");
        btmBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBackActionPerformed(evt);
            }
        });

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Faculty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCourse);
        if (tblCourse.getColumnModel().getColumnCount() > 0) {
            tblCourse.getColumnModel().getColumn(0).setResizable(false);
            tblCourse.getColumnModel().getColumn(1).setResizable(false);
        }

        btmAdd1.setBackground(new java.awt.Color(0, 153, 102));
        btmAdd1.setText("Add");
        btmAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAdd1ActionPerformed(evt);
            }
        });

        cmbcourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcourseItemStateChanged(evt);
            }
        });

        tblFacultyScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseName", "Faculty", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblFacultyScore);
        if (tblFacultyScore.getColumnModel().getColumnCount() > 0) {
            tblFacultyScore.getColumnModel().getColumn(0).setResizable(false);
            tblFacultyScore.getColumnModel().getColumn(1).setResizable(false);
            tblFacultyScore.getColumnModel().getColumn(2).setResizable(false);
        }

        btmAdd2.setBackground(new java.awt.Color(0, 153, 102));
        btmAdd2.setText("Add");
        btmAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAdd2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Instructor:");

        instructorLbl.setText("       ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblpromotion, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblworkyear, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblpromotion3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblpromotion2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtstartSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtpromotiontime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtworkyear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtcurrentsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addComponent(btmsave))
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbltop3)
                                        .addGap(34, 34, 34)
                                        .addComponent(cmbcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(instructorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFacultyScore, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btmAdd2)
                                    .addComponent(btmAdd1))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmBack)
                        .addGap(34, 34, 34)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btmBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblworkyear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpromotiontime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpromotion3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcurrentsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpromotion2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstartSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmsave))
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltop3)
                    .addComponent(cmbcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(instructorLbl)
                    .addComponent(btmAdd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmAdd2)
                    .addComponent(txtFacultyScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtworkyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtworkyearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtworkyearActionPerformed

    private void txtpromotiontimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpromotiontimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpromotiontimeActionPerformed

    private void txtcurrentsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcurrentsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcurrentsalaryActionPerformed

    private void txtstartSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartSalaryActionPerformed

    private void btmsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmsaveActionPerformed
        // TODO add your handling code here:
        student.getEmploymenthistory().setCurrentSalary(Double.valueOf(txtcurrentsalary.getText()));
        student.getEmploymenthistory().setPromotionsTimes(Double.valueOf(txtpromotiontime.getText()));
        student.getEmploymenthistory().setStartsalary(Double.valueOf(txtstartSalary.getText()));
        student.getEmploymenthistory().setWorkyears(Double.valueOf(txtworkyear.getText()));
        department.getstudentDirectory().addPromotion(Double.valueOf(txtpromotiontime.getText()));
        this.complete = true;
        JOptionPane.showMessageDialog(this, "This Form Saved."); 
    }//GEN-LAST:event_btmsaveActionPerformed

    private void btmBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBackActionPerformed
        main.getCardLayout().previous(main.getCards());
        main.getCards().remove(main.smjp.form);
        
    }//GEN-LAST:event_btmBackActionPerformed

    private void btmAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAdd1ActionPerformed
        // TODO add your handling code here:
        CourseOffer co = (CourseOffer) cmbcourse.getSelectedItem();
        for(CourseOffer c : student.getRelevent()){
            if(c.equals(co)){
                JOptionPane.showMessageDialog(this, "you have already picked this course!"); 
                return;
            }
        }
        co.getCourse().addRelevent();
        student.getRelevent().add(co);
        JOptionPane.showMessageDialog(this, "pick course success!"); 
        populateStudentCourses();
               
    }//GEN-LAST:event_btmAdd1ActionPerformed

    public void populateFacultyScore(){
        DefaultTableModel model = (DefaultTableModel) tblFacultyScore.getModel();
        model.setRowCount(0);        
        ArrayList<FacultyProfile> fp = new ArrayList();
        for(CourseLoad cl : student.getTranscript().getAllCourses()){
            Object row[] = new Object[3];
            row[0] = cl.getCourseOffer().getCourse().getName();
            row[1] = cl.getCourseOffer().getFacultyProfile().getPerson().getName();
            row[2] = cl.getCourseOffer().getFacultyProfile().getAverageScore();
            fp.add(cl.getCourseOffer().getFacultyProfile());
            model.addRow(row);
            
                
        }
    }
    private void btmAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAdd2ActionPerformed
        // TODO add your handling code here:
        CourseOffer co = (CourseOffer) cmbcourse.getSelectedItem();
        for(CourseOffer course : c){
            if(course.equals(co)){
                JOptionPane.showMessageDialog(this, "you have already evaluate this instructor for this course!"); 
                return;
            }

        }
        try{
            double score = Double.parseDouble(txtFacultyScore.getText());
            System.out.println(score);
            if(score>10 || score < 0){
                JOptionPane.showMessageDialog(this, "Please enter only 1-10"); 
                return;
            }
            co.getFacultyProfile().addScore(score);
            JOptionPane.showMessageDialog(this, "Evaluation success!"); 
            c.add(co);
        populateFacultyScore();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please use numbers only"); 
        }
        
        
    }//GEN-LAST:event_btmAdd2ActionPerformed

    private void cmbcourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcourseItemStateChanged
        // TODO add your handling code here:
        CourseOffer co = (CourseOffer) cmbcourse.getSelectedItem();
        instructorLbl.setText(co.getFacultyProfile().getPerson().getName());
    }//GEN-LAST:event_cmbcourseItemStateChanged

    @Override
    public String toString(){
        return "Student";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAdd1;
    private javax.swing.JButton btmAdd2;
    private javax.swing.JButton btmBack;
    private javax.swing.JButton btmsave;
    private javax.swing.JComboBox<CourseOffer> cmbcourse;
    private javax.swing.JLabel instructorLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblpromotion;
    private javax.swing.JLabel lblpromotion2;
    private javax.swing.JLabel lblpromotion3;
    private javax.swing.JLabel lbltop3;
    private javax.swing.JLabel lblworkyear;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTable tblFacultyScore;
    private javax.swing.JTextField txtFacultyScore;
    private javax.swing.JTextField txtcurrentsalary;
    private javax.swing.JTextField txtpromotiontime;
    private javax.swing.JTextField txtstartSalary;
    private javax.swing.JTextField txtworkyear;
    // End of variables declaration//GEN-END:variables
}
