/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.student;

import info5100.university.example.College;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.EmploymentHistory.EmploymentHistory;
import info5100.university.example.Persona.StudentProfile;
import ui.MainJframe;

/**
 *
 * @author HYR
 */
public class StudentManage extends javax.swing.JPanel {

    /**
     * Creates new form StudentManage
     */
    StudentManage smjp;
    Department department;
    MainJframe main;
    CourseAssignment cajp;
    Form form;
    StudentProfile studentProfile;
    CourseSchedule courseSchedule;
    EmploymentHistory employmentHistory;
    
    public StudentManage(Department d, MainJframe m,StudentProfile student) {
        initComponents();
        department = d;
        main = m;
        studentProfile = student;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmCourseSelection = new javax.swing.JButton();
        btmForm = new javax.swing.JButton();
        btmLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        btmCourseSelection.setBackground(new java.awt.Color(204, 204, 255));
        btmCourseSelection.setText("Course Selection");
        btmCourseSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCourseSelectionActionPerformed(evt);
            }
        });

        btmForm.setBackground(new java.awt.Color(255, 204, 204));
        btmForm.setText("Graduate student Survey");
        btmForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmFormActionPerformed(evt);
            }
        });

        btmLogout.setBackground(new java.awt.Color(204, 51, 0));
        btmLogout.setText("Logout");
        btmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btmLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btmCourseSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btmForm, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btmLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btmCourseSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btmForm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btmCourseSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCourseSelectionActionPerformed
        this.cajp = new CourseAssignment(department, main, courseSchedule,studentProfile);
        main.getCards().add(cajp);
        main.getCardLayout().next(main.getCards());
    }//GEN-LAST:event_btmCourseSelectionActionPerformed

    private void btmFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmFormActionPerformed
        this.form = new Form(studentProfile, main,employmentHistory,department, courseSchedule);
        main.getCards().add(form);
        main.getCardLayout().next(main.getCards());
    }//GEN-LAST:event_btmFormActionPerformed

    private void btmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLogoutActionPerformed
        main.getCardLayout().previous(main.getCards());
        main.getCards().remove(main.smjp);
    }//GEN-LAST:event_btmLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCourseSelection;
    private javax.swing.JButton btmForm;
    private javax.swing.JButton btmLogout;
    // End of variables declaration//GEN-END:variables
}
