/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin;

import info5100.university.example.College;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import ui.MainJframe;

/**
 *
 * @author HYR
 */
public class Facultyrank extends javax.swing.JPanel {

    /**
     * Creates new form Facultyrank
     */
    MainJframe main;
    AdminWorkAreaJpanel admin;
    College college;
    public Facultyrank(MainJframe main, AdminWorkAreaJpanel admin, College college) {
        initComponents();
        this.main = main;
        this.admin = admin;
        this.college = college;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultyRank = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        btmback.setBackground(new java.awt.Color(204, 51, 0));
        btmback.setText("back");
        btmback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmbackActionPerformed(evt);
            }
        });

        tblFacultyRank.setAutoCreateRowSorter(true);
        tblFacultyRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty Name", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFacultyRank);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmback, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmback, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btmbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmbackActionPerformed
        // TODO add your handling code here:
        main.getCardLayout().previous(main.getCards());
        main.getCards().remove(admin.frjp);
    }//GEN-LAST:event_btmbackActionPerformed
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblFacultyRank.getModel();
        model.setRowCount(0);  
        HashMap<String, Double> hm = new HashMap<String, Double>(); 
        for(Department department: college.getDepartmentCatalog().getDepartmentCatalog()){
            for(FacultyProfile fp : department.getFacultyDirectory().getTeacherlist()){
                hm.put(fp.getPerson().getName(), fp.getAverageScore());
            }
        }
        
        Map<String, Double> hm1 = sortByValue(hm); 
        for(Map.Entry<String, Double> en : hm1.entrySet()){
            Object row[] = new Object[2];
            row[0] = en.getKey();
            row[1] = en.getValue();
            model.addRow(row);
        }
       
        
    }
    public HashMap<String, Double> sortByValue(HashMap<String, Double> hm) 
    { 
        LinkedList<Map.Entry<String, Double> > list = 
               new LinkedList<Map.Entry<String, Double> >(hm.entrySet()); 
 
        Collections.sort(list, new Comparator<Map.Entry<String, Double> >() { 
            public int compare(Map.Entry<String, Double> o1,  
                               Map.Entry<String, Double> o2) 
            { 
                return (o1.getValue()).compareTo(o2.getValue()); 
            } 
        }); 
 
        HashMap<String, Double> temp = new LinkedHashMap<String, Double>(); 
        for (Map.Entry<String, Double> aa : list) { 
            temp.put(aa.getKey(), aa.getValue()); 
        } 
        return temp; 
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFacultyRank;
    // End of variables declaration//GEN-END:variables
}
